version: "3"
services:
  venkypostgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - venky-network
    environment:
      - POSTGRES_USER=venkyuser
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=Ganesh20022002

  frontend:
    image: sowmyavenky/spring-jpa:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://venkypostgres:5432/testdb
      - spring.datasource.username=venkyuser
      - spring.datasource.password=Ganesh20022002
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      - venky-network
    depends_on:
      - venkypostgres

networks:
  venky-network:
